
/* listbox.h	   Created:    1990-10-11  Revised:    1993-03-25	*/

/* Prominare Designer Custom Control Example Constants Header		*/

/* Copyright ¸ 1989-1993  Prominare Inc.  All Rights Reserved.		*/


/* --- Miscellaneous Constants ----------------------------------------	*/

#define	DID_HELP	      3	   /* Help Push	Button ID		*/
#define	DID_IDLIST	     10	   /* ID List Push Button ID		*/
#define	DID_PRESPARAM	     11	   /* Presentation Push	Button ID	*/

#define	CB_VISIBLE	    256	   /* Visible Check Box	ID		*/
#define	CB_GROUP	    257	   /* Group Check Box ID		*/
#define	CB_DISABLED	    258	   /* Disabled Check Box ID		*/
#define	CB_TABSTOP	    259	   /* Tab Stop Check Box ID		*/

#define	IDS_VISIBLE	    512	   /* Visible Style String		*/
#define	IDS_GROUP	    513	   /* Group Style String		*/
#define	IDS_DISABLED	    514	   /* Disabled Style String		*/
#define	IDS_TABSTOP	    515	   /* Tab Stop Style String		*/

/* --- Control Dialogue	-----------------------------------------------	*/

#define	DLG_CTRLUSER	   1000	   /* User Defined Dialog		*/
#define	EF_TEXT		   1001	   /* Control Text Entry Field		*/
#define	EF_SYMBOL	   1002	   /* Window ID	Entry Field		*/
#define	EF_SYMBOLVALUE	   1003	   /* ID Value Entry Field		*/
#define	MLE_LIST	   4050	   /* Data List	MLE			*/
#define	MLE_TEXT	   260
#define	CB_LS_MULTIPLESEL  4061	   /* Multiple Selection Check Box	*/
#define	CB_LS_OWNERDRAW	   4062	   /* User Redraw Check	Box		*/
#define	CB_LS_NOADJUSTPOS  4063	   /* No Adjust	Position Check Box	*/
#define	CB_LS_HORZSCROLL   4064	   /* Horizontal Scroll	Check Box	*/
#define	CB_LS_EXTENDEDSEL  4065	   /* Extended Selection Check Box [2.x]*/
#define	CB_LSXS_CHECKBOX   4066	   /* Extended Style			*/
#define	EF_SND1		   1004	   /* Single Click Sound		*/
#define	EF_SND2		   1005	   /* Double Click Sound		*/

/* --- Control Dialogue	-----------------------------------------------	*/

#define	DLG_CTRLANLUSER	   1100	   /* User Defined Dialog		*/

/* --- Styles Strings Definitions -------------------------------------	*/

#define	IDS_LS_MULTIPLESEL     32
#define	IDS_LS_OWNERDRAW       33
#define	IDS_LS_NOADJUSTPOS     34
#define	IDS_LS_HORZSCROLL      35
#define	IDS_LS_EXTENDEDSEL     36
#define	IDS_LSXS_CHECKBOX      37
